# Generated by Django 3.2.9 on 2021-11-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0002_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_list', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='petapp.product')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_add', to='petapp.product')),
            ],
            options={
                'verbose_name_plural': 'Carts',
                'ordering': ('-price',),
            },
        ),
    ]
