# Generated by Django 3.2.9 on 2021-11-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileinfo',
            old_name='image',
            new_name='image1',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
