# Generated by Django 3.2.9 on 2021-11-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0004_auto_20211124_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='selectedimage5',
        ),
    ]
